version: "3.8"
services:
  backend:
    build: tests
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    networks:
      - flask_network
networks:
  flask_network:
    driver: bridge
